export { homePage } from './home'
export { servicesPage } from './services'
export { servicePage } from './service'
export { capabilitiesPage } from './capabilities'
export { aboutPage } from './about'
export { contactPage } from './contact'
export { notFoundPage } from './notfound'
export { privacyPage } from './privacy'
export { termsPage } from './terms'
export { robotsTxt, sitemapXml } from './robots'
